#BMI local app config - do not commit (lang/theme/encrypted-login only)
#Thu Jul 16 20:52:56 CST 2026
ui.remember.pwdHash=e0eada1ce6e9d7bf844a42b7b76285ce8cccb872cb3fd532fe83815e8b05ccd1
ui.remember.user=Saints
